### ISSUE TITLE
Test PHP

### ISSUE THREAD

**Issue by negoziator** [billysbilling/common-php#5]
@phptinker

```php
echo "What's up Ageras";
```

**Comment by phptinker** [comment]
@negoziator, here's the evaluated code:

```
What's up Ageras
```

<details>
<summary>We evaluated this code</summary>

```php
echo "What's up Ageras";
```
</details>

Check out [Tinkerwell](https://tinkerwell.app) for even easier code evaluation.

**Comment by Bottelet** [comment]
@phptinker
`echo "What's up Billy!";`

**Comment by negoziator** [comment]
haha @Bottelet 

You  need to do the "```php" thing

**Comment by Bottelet** [comment]
@phptinker
```php
echo "what's up booois!";
```

**Comment by negoziator** [comment]
@phptinker
```php
echo "what's up booois!";
```

**Comment by negoziator** [comment]
@Bottelet Litterally copy/paste af din .. let's see 👀 

Måske virker det kun én gang pr tråd 😂
